version: "3.1"
services:
  web:
    build: php
    ports:
        - "80:80"
    volumes:
        - ./../.:/src
        - ./php/nginxConf/:/etc/nginx/conf.d/
        - /dev/log:/dev/log
        - ./php/nginxDefault/nginx.conf:/etc/nginx/nginx.conf
    environment:
        - ENV=${ENV}
    links:
        - db
  
  node:
    tty: true
    build: node
    ports:
      - "8080:8080"
      - "3000:3000"

  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=changeIt
      - MYSQL_DATABASE=db
      - MYSQL_USER=bg
      - MYSQL_PASSWORD=changeIt
      - TERM=dumb
    volumes:
      - ./db:/etc/mysql/conf.d
    tty: true
    logging:
      driver: syslog